config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete 'users/sign_out', to: 'devise/sessions#destroy'
  end
  root to: 'prototypes#index'
  resources :prototypes, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def index
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end
  
  def create
    @Prototype.create(prototype_params)
    if @prototype.save
      redirect_to prototypes_path, notice: 'Prototype was successfully created.'
    else
      render :new
    end
  end
  
  private

  def prototype_params
    params.require(:prototype).permit(:name, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <div class="nav__right">
            <% if user_signed_in? %>
              <%= form_with url: destroy_user_session_path, method: :delete, class: "nav__logout-form", local: true do %>
                <%= submit_tag "ログアウト", class: "nav__logout" %>
              <% end %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            <% else %>
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h1>こんにちは、<%= current_user.name %>さん</h1>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <%= link_to 'New Proto', new_proto_path %>
<% else %>
  <h1>Welcome to our website</h1>
  <%= link_to 'ログイン', new_user_session_path %>
  <%= link_to '新規登録', new_user_registration_path %>
<% end %>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、 
        <%= link_to "#{current_user.name}さん", root_path, class: :greeting__link%>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    
    <div class="card__wrapper">
      <% @prototypes.each do |prototype| %>
        <div class="card">
          <h2 class="card__title"><%= prototype.name %></h2>
          <p class="card__description"><%= prototype.description %></p>
          <% if prototype.user %>
            <p class="card__user">
              投稿者: <%= link_to prototype.user.name, user_path(prototype.user) %>
            </p>
          <% else %>
            <p class="card__user">投稿者情報なし</p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @tweet, local: true) do |form| %>
      <%= form.text_field :name, placeholder: "Nickname" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>